name: Build Windows

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  QT_VERSION: 6.9.1

defaults:
  run:
    shell: msys2 {0}

jobs:
  build:
    name: '🚧 Build MEASaveEditor'
    runs-on: 'windows-latest'
    steps:
      - name: '📥 Setup msys2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            git
            make
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
            extra-cmake-modules:p
            zlib:p
      - name: '📥 Install Qt'
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_mingw
          cache: true
      - name: '✅ Checkout repo'
        uses: actions/checkout@v4
        with:
          path: app-source
      - name: '⚙️ Configure'
        run: |
          cmake -S app-source -B app-build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH="$PWD/ecm-prefix;$QT_ROOT_DIR" \
            -DCMAKE_INSTALL_PREFIX="$PWD/artifacts/MEASaveEditor"
      - name: '🚧 Build and Install'
        run: |
          cmake --build app-build --parallel
      - name: '📦 Install'
        run: |
          cmake --install app-build

          EXE_PATH="$PWD/artifacts/MEASaveEditor/bin/MEASaveEditor.exe"
          ZLIB_DLL=$(ldd "$EXE_PATH" | grep zlib1.dll | cut -d " " -f 3)
          cp "$ZLIB_DLL" "$PWD/artifacts/MEASaveEditor/bin"
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: MEASaveEditor
          path: artifacts